environment:
  matrix:

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu

matrix:
  fast_finish: true

init:
  - appveyor version

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows build

    install:
    - cmd: echo This is Windows-specific install

    before_build:
    - cmd: echo This is Windows-specific before_build

    build_script:
    - cmd: echo This is Windows-specific build_script

  -
    matrix:
      only:
        - job_name: Linux build

    install:
    - sh: echo This is Linux-specific install

    before_build:
    - sh: echo This is Linux-specific before_build

    build_script:
    - sh: echo This is Linux-specific build_script
