blank_issues_enabled: false
contact_links:
  - name: OpenHantek6022 Discussions
    url: https://github.com/OpenHantek/OpenHantek6022/discussions
    about: The place to discuss new ideas and ask for help
