name: Ubuntu_Check
# check if OH6022 builds on some recent Ubuntu LTS versions

on: [push]

env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  ubuntu_check:
    strategy:
      # do not stop on 1st fail
      fail-fast: false
      matrix:
        # ubuntu-16.04 is too old for our CMake
        os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Build Requirements
      shell: bash
      # Install build requirements
      run: sudo apt install g++ make cmake fakeroot rpm qttools5-dev libfftw3-dev binutils-dev libusb-1.0-0-dev libqt5opengl5-dev mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev

    - name: Create Build Environment
      shell: bash
      # Create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Now build the binary
      run: make -j4

    - name: Package
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Build packages as defined by the CMake configuration.
      run: fakeroot make -j4 package

    - uses: actions/upload-artifact@v2
      with:
        # create a zip file openhantek_ubuntu-xx.xx_nn.zip
        name: openhantek_${{matrix.os}}_${{github.run_number}}.zip
        path: ${{github.workspace}}/build/packages/

